### ISSUE TITLE
Allow to pass variables/arrays to options

### ISSUE THREAD

**Issue by platosinski** [robertfausk/behat-panther-extension#11]
PatherTestCaseTrait::startWebServer accepts $options and one of them can be array of env vars (https://github.com/symfony/panther/blob/39efc06a5958746844a523fb31f6cc5955b3c9e4/src/PantherTestCaseTrait.php#L116) but PantherConfiguration requires options to be scalar. Could you change scalarPrototype() inside addOptionsNode() to variablePrototype() (like you did it in addManagerOptionsNode())?

That change will allow to pass e.g. APP_ENV to Panther internal WebServerManager.

Additionally i would like to note that passing kernel_options to PantherDriver is useless, because these are not used, when PantherTestCaseTrait is used by class which doesn't extend KernelTestCase.

**Comment by robertfausk** [comment]
Thanks for your issue. I am currently at holidays. So I will have a deeper look at it next week.

**Comment by robertfausk** [comment]
@platosinski Have a look at ```v1.1.1``` by simply doing a ```composer update --with-dependencies robertfausk/behat-panther-extension``` :balloon:

**Comment by platosinski** [comment]
Great! Works like a charm! Thanks a lot!
