### ISSUE TITLE
Update composer.json to support Process ^6.0

### ISSUE THREAD

**Issue by Dragony** [robertfausk/behat-panther-extension#8]
Hello! We've used your library to setup a behat test suite.

Recently we've updated our PHP Version and other dependencies and we've run into a problem. Our newest Packages relies on symfony/process ^6.0. Currently your package `mink-panther-driver` has a dev release to also include the new process package. Sadly  the `behat-panther-extension` package does not have a release that includes the updated panther driver package.

Can you create a new version of `robertfausk/mink-panther-driver` and `robertfausk/behat-panther-extension` to include `symfony/process ^6.0` in the dependency chain, instead of `symfony/process ^5.0`?

I'm also happy to help and do the work, but most of it tagging a new version and doing a release. Something I can't do in a pull request.

Best regards from Switzerland!

**Comment by robertfausk** [comment]
Hi @Dragony! 

I've just released https://github.com/robertfausk/mink-panther-driver/releases/tag/v1.1.0. So it should be enough to require ```"robertfausk/behat-panther-extension": "~1.0"``` in your ```composer.json```.

If you still encounter an issue pls reopen or create a new issue.

Greetings from Dresden:)

**Comment by Dragony** [comment]
Thank you ver much, everything works great now! 😃🥳
